### ISSUE TITLE
No license set for the project

### ISSUE THREAD

**Issue by dstj** [stemarie/log4net.Azure#14]
There is no license set for this project's source code. There is not tons of code, and it's relatively straight forward, but could you please set a license to avoid any ambiguity. I suggest MIT or Apache2

**Comment by christianrondeau** [comment]
Agreed, this is very important as currently, theoretically nobody can safely use your project :)

https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license

Also, I love [MIT](http://opensource.org/licenses/MIT)!

**Comment by stemarie** [comment]
MIT License added

Thanks for the feedback

**Comment by christianrondeau** [comment]
Amazing, thanks :)
