### ISSUE TITLE
Assemblies not signed (does not have a strong name)

### ISSUE THREAD

**Issue by GlenBoonzaier** [stemarie/log4net.Azure#26]
I am getting the following warning from MSBuild:

CSC: Referenced assembly 'log4net.Appender.Azure, Version=1.2.1.23255, Culture=neutral, PublicKeyToken=null' does not have a strong name.

This is apparently because the assembly is not signed.

**Comment by stemarie** [comment]
That is correct, the Assembly is not signed
I may sign them in the future but am not planning to in the immediate future since this doesn't prevent the use of the library
Feel free to turn off the warning if you wish
