### ISSUE TITLE
Blob storage using AppendBlob

### ISSUE THREAD

**Issue by chriswill** [stemarie/log4net.Azure#30]
Currently logging to blob storage is done via adding a separate xml file to the specified blob container.  However, Azure storage now supports AppendBlobs, which are optimized for logging scenarios. 

http://blogs.msdn.com/b/windowsazurestorage/archive/2015/04/13/introducing-azure-storage-append-blob.aspx

Is there any interest in accepting a PR that implements this functionality?

**Comment by calmath** [comment]
I had the same requirement and have modified the code with a new Appender 'AzureApendBlobAppender'. I am testing this on our environments at the moment though would be happy to share the code (simple cut and paste with very minor code changes) so the this gets added to this core solution.

**Comment by stemarie** [comment]
Would love to add your code to the solution, feel free to create a push request when you feel it is ready

**Comment by stemarie** [comment]
Handled with 12101ef
