### ISSUE TITLE
Missing dependency on Microsoft.WindowsAzure.ConfigurationManager (≥ 3.1.0)

### ISSUE THREAD

**Issue by antongeorgiev** [stemarie/log4net.Azure#37]
Please add in the .nuspec file a dependency to Microsoft.WindowsAzure.ConfigurationManager (≥ 3.1.0) 

See the attached log for reference

[log4net.txt](https://github.com/stemarie/log4net.Azure/files/103671/log4net.txt)

**Comment by stemarie** [comment]
Pushed v1.4.1.0 to Nuget
