### ISSUE TITLE
How to add Custom columns ? 

### ISSUE THREAD

**Issue by kumaro** [stemarie/log4net.Azure#42]
Is it possible to Create and Log data to Custom columns on Azure tables ?

**Comment by anth12** [comment]
Yes. First you need to enable the setting `PropAsColumn` and ensure you do not have a `Layout` defined (https://github.com/stemarie/log4net.Azure/blob/master/log4net.Azure/AzureTableAppender.cs#L91)

    <param name="PropAsColumn" value="true" />

Now you just need to define the custom properties, you can use `log4net.ThreadContext.Properties` e.g.

    log4net.ThreadContext.Properties["Action"] = actionContext.ActionDescriptor.ActionName;

Another method you may wish to use is defining a new appender inheiring from `AzureTableAppender` to log common data e.g.

    public class CustomAzureTableAppender : log4net.Appender.AzureTableAppender
    {
        protected override void Append(LoggingEvent loggingEvent)
        {
            var context = HttpContext.Current; // Note HttpContext.Request will error on App_Start
            if (context != null)
            {
                loggingEvent.Properties["Url"] = context.Request.Url.AbsolutePath;
            }

            base.Append(loggingEvent);
        }
    }

And finally update your config

    <appender name="AzureTableAppender" type="Example.Logging.CustomAzureTableAppender, Example">

**Comment by kumaro** [comment]
Great, Thank you!

**Comment by HadiNass** [comment]
What can I do to remove columns that I don't need?

**Comment by Walid-Yahia** [comment]
Hi all,
I'm using this code to add a new column
log4net.ThreadContext.Properties["Action"] = actionContext.ActionDescriptor.ActionName;

How can I set the RowKey value of the entity?
