### ISSUE TITLE
ConnectionStringName doesn't work while using ConnectionString is ok

### ISSUE THREAD

**Issue by sunny00O** [stemarie/log4net.Azure#44]
when i use ConnectionStringName like below, it doesn't work
`<connectionStrings>`
`<add name="Log4Net.WindowsAzureStorage.ConnectionString" connectionString=****" />`
`</connectionStrings>`
  
`<log4net> 
...
<param name="ConnectionStringName" value="Log4Net.WindowsAzureStorage.ConnectionString" />
...
</log4net>`

but if i use the ConnectionString directly like below, it works, why?  is it because a lack of  <ConnectioType>?  but i don't know how to write the <ConnectioType>...
`<log4net> 
...
<param name="ConnectionString" value="****" />
...
</log4net>`

**Comment by xplorld** [comment]
facing the same problem too

**Comment by andrerav** [comment]
Hi,

I am having the same issue, but only when deploying the application as a worker role. Running it as a webjob or in a console works as expected. I will take a peek into the source and see if I can find the reason. I may have some ideas.

**Comment by andrerav** [comment]
Fixed (and verified) in this fork: https://github.com/andrerav/log4net.Azure/tree/issues/44/ConnectionStringNameDoesNotWork

I have also submitted a pull request. Let's hope @stemarie will accept it and push a nuget package ASAP :)

**Comment by stemarie** [comment]
Thanks for the Push,
I've pushed 1.4.2.0 to nuget.org
Enjoy!

**Comment by andrerav** [comment]
Great, thanks!

**Comment by andrerav** [comment]
Hi @stemarie,

I updated to the latest nuget package (1.4.2), but I couldn't get it to work. So I used ILSpy to inspect the assembly, and it seems the fix is not present in the assembly. Can you take a look at this? It's probably just a mishap in the packaging :)

Thanks,
Andreas

**Comment by stemarie** [comment]
Yes, I just retraced my steps and it looks like I changed the version number without putting in the new assembly. Sorry about that, let me fix it and upload a new, new version to nuget.

**Comment by andrerav** [comment]
Excellent, thank you very much! :)

**Comment by stemarie** [comment]
Should be good now, let me know if you have any issues with this new publish

076c56ab0a2a8e79e42a2e3295c773031f54a200
