### ISSUE TITLE
Azure table appender error

### ISSUE THREAD

**Issue by mihaivader** [stemarie/log4net.Azure#47]
Hi,

I'm trying to use the Azure Table storage appender but nothing gets added.
I've added 

`<add key="log4net.Internal.Debug" value="true"/>`

and 

```
<system.diagnostics>
    <trace>
     <listeners>
  <add
       name="textWriterTraceListener"
       type="System.Diagnostics.TextWriterTraceListener"
       initializeData="C:\dev\log4net.txt" />
       </listeners>
    </trace>
  </system.diagnostics>
```

and the error that I'm getting is this one 

> log4net:ERROR Could not create Appender [AzureTableAppender] of type [log4net.Appender.AzureTableAppender, log4net.Appender.Azure]. Reported error follows.
> Microsoft.WindowsAzure.Storage.StorageException: The remote server returned an error: (501) Not Implemented. ---> System.Net.WebException: The remote server returned an error: (501) Not Implemented.

Any ideas ? 

Thanks

**Comment by stemarie** [comment]
I am unable to reproduce this problem, all tests pass. Please provide clear reproduction steps and I will re-investigate.
Thanks

**Comment by mihaivader** [comment]
Hey.
Found the issue: I was trying to write to table storage on an account of type BlobStorage instead of General.
It would be nice if their error was a bit more explicit.

Thanks :)

**Comment by stemarie** [comment]
Perfect thanks, I'll close this issue

**Comment by jpierson** [comment]
I'm getting the same issue but I have set up my storage account as having *general* account type. I did make this a _Resource Managment_ storage account, does that matter? Is this appender in some way only compatible with classic storage accounts?

I get the feeling that the `StorageException` is the general result we will get when there is an issue connecting to the storage account.

**Comment by jpierson** [comment]
I opened a new issue #59 in favor of hijacking this closed one ;)
