### ISSUE TITLE
When built in Release mode

### ISSUE THREAD

**Issue by svilenstefanov** [stemarie/log4net.Azure#50]
Hi,

When the project is built in debug mode the logging works fine. However when deployed in release mode it doesn't log. Even on the dev machine doesn't log when mode is release. 

Do you have any ideas why is that ? 

Thanks

**Comment by jorupp** [comment]
Have you tried a different logger (like log4net's built-in file appenders)?  Does it only happen when your *app* is built in release mode, or when log4net.Azure is?

**Comment by dhananjaykadam** [comment]
same happening with me as well, When I build it with release mode it doesn't log. Files are there for log4net.config, dll and one xml
